export const BUYING_LIST_REQUEST = 'BUYING_LIST_REQUEST'
export const BUYING_LIST_SUCCESS = 'BUYING_LIST_SUCCESS'
export const BUYING_LIST_FAIL = 'BUYING_LIST_FAIL'

export const BUYING_DETAILS_REQUEST = 'BUYING_DETAILS_REQUEST'
export const BUYING_DETAILS_SUCCESS = 'BUYING_DETAILS_SUCCESS'
export const BUYING_DETAILS_FAIL = 'BUYING_DETAILS_FAIL'
export const BUYING_DETAILS_RESET = 'BUYING_DETAILS_RESET'

export const BUYING_DELETE_REQUEST = 'BUYING_DELETE_REQUEST'
export const BUYING_DELETE_SUCCESS = 'BUYING_DELETE_SUCCESS'
export const BUYING_DELETE_FAIL = 'BUYING_DELETE_FAIL'

export const BUYING_CREATE_REQUEST = 'BUYING_CREATE_REQUEST'
export const BUYING_CREATE_SUCCESS = 'BUYING_CREATE_SUCCESS'
export const BUYING_CREATE_FAIL = 'BUYING_CREATE_FAIL'
export const BUYING_CREATE_RESET = 'BUYING_CREATE_RESET'

export const BUYING_UPDATE_REQUEST = 'BUYING_UPDATE_REQUEST'
export const BUYING_UPDATE_SUCCESS = 'BUYING_UPDATE_SUCCESS'
export const BUYING_UPDATE_FAIL = 'BUYING_UPDATE_FAIL'
export const BUYING_UPDATE_RESET = 'BUYING_UPDATE_RESET'

export const BUYING_CREATE_REVIEW_REQUEST = 'BUYING_CREATE_REVIEW_REQUEST'
export const BUYING_CREATE_REVIEW_SUCCESS = 'BUYING_CREATE_REVIEW_SUCCESS'
export const BUYING_CREATE_REVIEW_FAIL = 'BUYING_CREATE_REVIEW_FAIL'
export const BUYING_CREATE_REVIEW_RESET = 'BUYING_CREATE_REVIEW_RESET'

export const BUYING_TOP_REQUEST = 'BUYING_TOP_REQUEST'
export const BUYING_TOP_SUCCESS = 'BUYING_TOP_SUCCESS'
export const BUYING_TOP_FAIL = 'BUYING_TOP_FAIL'