export const COMMERCIAL_LIST_REQUEST = 'COMMERCIAL_LIST_REQUEST'
export const COMMERCIAL_LIST_SUCCESS = 'COMMERCIAL_LIST_SUCCESS'
export const COMMERCIAL_LIST_FAIL = 'COMMERCIAL_LIST_FAIL'

export const COMMERCIAL_DETAILS_REQUEST = 'COMMERCIAL_DETAILS_REQUEST'
export const COMMERCIAL_DETAILS_SUCCESS = 'COMMERCIAL_DETAILS_SUCCESS'
export const COMMERCIAL_DETAILS_FAIL = 'COMMERCIAL_DETAILS_FAIL'
export const COMMERCIAL_DETAILS_RESET = 'COMMERCIAL_DETAILS_RESET'

export const COMMERCIAL_DELETE_REQUEST = 'COMMERCIAL_DELETE_REQUEST'
export const COMMERCIAL_DELETE_SUCCESS = 'COMMERCIAL_DELETE_SUCCESS'
export const COMMERCIAL_DELETE_FAIL = 'COMMERCIAL_DELETE_FAIL'

export const COMMERCIAL_CREATE_REQUEST = 'COMMERCIAL_CREATE_REQUEST'
export const COMMERCIAL_CREATE_SUCCESS = 'COMMERCIAL_CREATE_SUCCESS'
export const COMMERCIAL_CREATE_FAIL = 'COMMERCIAL_CREATE_FAIL'
export const COMMERCIAL_CREATE_RESET = 'COMMERCIAL_CREATE_RESET'

export const COMMERCIAL_UPDATE_REQUEST = 'COMMERCIAL_UPDATE_REQUEST'
export const COMMERCIAL_UPDATE_SUCCESS = 'COMMERCIAL_UPDATE_SUCCESS'
export const COMMERCIAL_UPDATE_FAIL = 'COMMERCIAL_UPDATE_FAIL'
export const COMMERCIAL_UPDATE_RESET = 'COMMERCIAL_UPDATE_RESET'

export const COMMERCIAL_CREATE_REVIEW_REQUEST = 'COMMERCIAL_CREATE_REVIEW_REQUEST'
export const COMMERCIAL_CREATE_REVIEW_SUCCESS = 'COMMERCIAL_CREATE_REVIEW_SUCCESS'
export const COMMERCIAL_CREATE_REVIEW_FAIL = 'COMMERCIAL_CREATE_REVIEW_FAIL'
export const COMMERCIAL_CREATE_REVIEW_RESET = 'COMMERCIAL_CREATE_REVIEW_RESET'

export const COMMERCIAL_TOP_REQUEST = 'COMMERCIAL_TOP_REQUEST'
export const COMMERCIAL_TOP_SUCCESS = 'COMMERCIAL_TOP_SUCCESS'
export const COMMERCIAL_TOP_FAIL = 'COMMERCIAL_TOP_FAIL'