export const RENTING_LIST_REQUEST = 'RENTING_LIST_REQUEST'
export const RENTING_LIST_SUCCESS = 'RENTING_LIST_SUCCESS'
export const RENTING_LIST_FAIL = 'RENTING_LIST_FAIL'

export const RENTING_DETAILS_REQUEST = 'RENTING_DETAILS_REQUEST'
export const RENTING_DETAILS_SUCCESS = 'RENTING_DETAILS_SUCCESS'
export const RENTING_DETAILS_FAIL = 'RENTING_DETAILS_FAIL'

export const RENTING_DELETE_REQUEST = 'RENTING_DELETE_REQUEST'
export const RENTING_DELETE_SUCCESS = 'RENTING_DELETE_SUCCESS'
export const RENTING_DELETE_FAIL = 'RENTING_DELETE_FAIL'

export const RENTING_CREATE_REQUEST = 'RENTING_CREATE_REQUEST'
export const RENTING_CREATE_SUCCESS = 'RENTING_CREATE_SUCCESS'
export const RENTING_CREATE_FAIL = 'RENTING_CREATE_FAIL'
export const RENTING_CREATE_RESET = 'RENTING_CREATE_RESET'

export const RENTING_UPDATE_REQUEST = 'RENTING_UPDATE_REQUEST'
export const RENTING_UPDATE_SUCCESS = 'RENTING_UPDATE_SUCCESS'
export const RENTING_UPDATE_FAIL = 'RENTING_UPDATE_FAIL'
export const RENTING_UPDATE_RESET = 'RENTING_UPDATE_RESET'

export const RENTING_CREATE_REVIEW_REQUEST = 'RENTING_CREATE_REVIEW_REQUEST'
export const RENTING_CREATE_REVIEW_SUCCESS = 'RENTING_CREATE_REVIEW_SUCCESS'
export const RENTING_CREATE_REVIEW_FAIL = 'RENTING_CREATE_REVIEW_FAIL'
export const RENTING_CREATE_REVIEW_RESET = 'RENTING_CREATE_REVIEW_RESET'

export const RENTING_TOP_REQUEST = 'RENTING_TOP_REQUEST'
export const RENTING_TOP_SUCCESS = 'RENTING_TOP_SUCCESS'
export const RENTING_TOP_FAIL = 'RENTING_TOP_FAIL'